### PR TITLE
bug fix: password assigned to username

### PR DESCRIPTION
**Pull request by linux-china**
Fix password assigned to username wrongly in ConnectionFactoryBuilder.java
```
                String password = properties.determinePassword();
		if (StringUtils.hasText(password)) {
			builder.option(ConnectionFactoryOptions.PASSWORD, username);
		}
```

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@linux-china Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects-experimental/spring-boot-r2dbc&pullRequestId=16)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects-experimental/spring-boot-r2dbc&pullRequestId=16) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@linux-china Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects-experimental/spring-boot-r2dbc&pullRequestId=16)!

**Comment by mp911de** [comment]
Thanks a lot. Can you provide also a test along with this change?

**Comment by mp911de** [comment]
That's merged now.

**Pull request closed without merging**
